upgrade golang.org/x/tools
masibw/goone pull request #67
Opened 2022-07-19 12:12 UTC by Saza-ku

https://github.com/golang/go/issues/49164 によると、#66 は x/tools/go/packages をアップグレードすることで直るようでした。そのため、以下のようにして x/tools/go/packages をアップグレードしました。

```sh
go get golang.org/x/tools/go/analysis@latest
go mod tidy
```

この状態でビルドしてみると、正常に実行できました。

```sh
$ go vet -vettool=/path/to/goone ./...
# hoge
./main.go:38:13: this query is called in a loop
```

This PR fixes #66 .

2022-07-19 14:05 UTC, masibw commented
PRありがとうございます:pray:
いただいたPRのlintが通らなかったのでCIの修正をしていたんですが、testのCIが回らず手元で実行してもtestが落ちるのでちょっと原因調査中です:bow:
（CIの修正と分けてもよかったんですが、多分CIの修正 = バージョンアップすると頂いたcommitが不要になってしまうと思ったのでこのPRで作業してしまいました）

2022-07-19 14:22 UTC, masibw requested changes
testが通るまで一旦 request changes

2022-07-19 16:19 UTC, masibw approved these changes
右往左往してしまいましたが、無事ローカルでテストが通るようになったのでマージしたいと思います。
ありがとうございました

2022-07-19 16:20 UTC, merged

2022-07-20 11:38 UTC, Saza-ku commented
よかったです👍  
ありがたく使わせていただきます🙏